# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0002_esptest'),
    ]

    operations = [
        migrations.AddField(
            model_name='esptest',
            name='sensr',
            field=models.CharField(default='NULL', max_length=128),
        ),
    ]
