# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0004_esptest_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esptest',
            old_name='sensr',
            new_name='isFall',
        ),
        migrations.RenameField(
            model_name='esptest',
            old_name='val',
            new_name='isSafe',
        ),
        migrations.AddField(
            model_name='esptest',
            name='isTremor',
            field=models.CharField(default='NULL', max_length=128),
        ),
        migrations.AddField(
            model_name='esptest',
            name='latValue',
            field=models.CharField(default='NULL', max_length=128),
        ),
        migrations.AddField(
            model_name='esptest',
            name='longValue',
            field=models.CharField(default='NULL', max_length=128),
        ),
        migrations.AddField(
            model_name='esptest',
            name='safeDist',
            field=models.CharField(default='NULL', max_length=128),
        ),
    ]
