# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0005_auto_20180506_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='esptest',
            name='bpm',
            field=models.CharField(default='NULL', max_length=128),
        ),
    ]
