# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0006_esptest_bpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTremor', models.CharField(default='NULL', max_length=128)),
                ('isFall', models.CharField(default='NULL', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GpsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latValue', models.CharField(default='NULL', max_length=128)),
                ('longValue', models.CharField(default='NULL', max_length=128)),
                ('safeDist', models.CharField(default='NULL', max_length=128)),
                ('isSafe', models.CharField(default='NULL', max_length=128)),
                ('bpm', models.CharField(default='NULL', max_length=128)),
            ],
        ),
    ]
