# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0007_accmodel_gpsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
