# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0008_gpsmodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsmodel',
            name='updated_at',
        ),
    ]
