# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0009_remove_gpsmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
