# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0011_auto_20180511_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accmodel',
            name='upd',
            field=models.CharField(default=datetime.datetime(2018, 5, 11, 17, 24, 0, 800009, tzinfo=utc), max_length=128),
        ),
    ]
