# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0013_auto_20180511_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accmodel',
            name='upd',
        ),
        migrations.AddField(
            model_name='accmodel',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
