# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0015_auto_20180512_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
